### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by kheaactua** [seandroid-analytics/selint#3]
Hi, is this project "dead"?  I tried using it on my AOSP 11 build tree.  It took me a while to get the dependencies working, but it seems to just not work.

I haven't tried any other SELint tool as I'm not sure how well they'd work for Android policies.

The error I got at the furthest point I got were:
```
Using default configuration file "${ANDROID_BUILD_TOP}/vendor/ford/system/fnv/external/selint/config.py"...
CRITICAL:root:Directory "${ANDROID_BUILD_TOP}/build/target/board/generic/sepolicy" does not exist or is not readable/traversable!
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/28.0/private/genfs_contexts: 179: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/28.0/private/genfs_contexts: 207: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/29.0/private/genfs_contexts: 202: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/29.0/private/genfs_contexts: 242: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/29.0/private/genfs_contexts: 247: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/29.0/private/genfs_contexts: 287: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/30.0/private/genfs_contexts: 212: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/30.0/private/genfs_contexts: 252: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/30.0/private/genfs_contexts: 258: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/30.0/private/genfs_contexts: 298: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/private/genfs_contexts: 212: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/private/genfs_contexts: 252: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/private/genfs_contexts: 258: 
m4: ${ANDROID_BUILD_TOP}/system/sepolicy/private/genfs_contexts: 298: 
${ANDROID_BUILD_TOP}/system/sepolicy/prebuilts/api/27.0/private/security_classes:11:ERROR 'duplicate declaration of class security' at token 'security' on line 156:
class security

Traceback (most recent call last):
  File "./selint", line 284, in <module>
    ALL_POLICY_FILES, args.extra_defs, load_neverallows=False)
  File "${ANDROID_BUILD_TOP}/vendor/ford/system/fnv/external/selint/policysource/policy.py", line 88, in __init__
    self._policy = setools.policyrep.SELinuxPolicy(self.policyconf)
  File "${ANDROID_BUILD_TOP}/prebuilts/python/linux-x86/2.7.5/lib/python2.7/site-packages/setools/policyrep/__init__.py", line 92, in __init__
    self._load_policy(policyfile)
  File "${ANDROID_BUILD_TOP}/prebuilts/python/linux-x86/2.7.5/lib/python2.7/site-packages/setools/policyrep/__init__.py", line 125, in _load_policy
    format(filename, err))
setools.policyrep.exception.InvalidPolicy: Error opening policy file "/tmp/tmppgQk6z/policy.conf": Invalid policy.
```

**Comment by Fbonazzi** [comment]
Hi, I am sorry to say that this project is not maintained any longer.

I left Aalto University in 2017, and I have not been following SELinux developments since. I am afraid I cannot say how SELinux policies on Android have changed since then, and what it would take to make this tool work on modern policies.

Furthermore, SELint was using [setools](https://github.com/TresysTechnology/setools) for policy parsing, and I do not know how or how much that project has changed in the intervening years.

I am happy to help with my old domain knowledge, if I can (and if I have any left).

Two things jump to my eye:
1. is there an issue with permissions on ${ANDROID_BUILD_TOP}/build/target/board/generic/sepolicy? The folder should be readable and traversable. Can you try to see if there's anything funny with that?
2. Is there really a duplicate declaration of the "security" class in the policy? Is this something that is supported in modern policies, or is this just a mistake in e.g. including too many files belonging to multiple policies?

**Comment by kheaactua** [comment]
Hi Filippo, no problem.  I can't answer any questions now from any of my grad work. :)

1. My permissions are fine (completely readable/traversable)
2. hmm, I'm not sure, I'll have to dive in and see.  I don't spend much time in the API policies.

I'm really not sure how much Android SELinux have changed in the last few years.  I'm relatively new to Android and SELinux, but I have seen that things change quickly.

I believe Microsoft is developing an SELint tool too, except it doesn't support Android. :(

Thanks for the response though.  I'll see if I can poke around a little more with the code.  Especially when working with the HAL, the policies get pretty complex so any tool that helps with that is welcome. :)

**Comment by Fbonazzi** [comment]
I was under the impression that sometime in 2017 or 2018 Android had aligned their SELinux policies to be compatible with upstream SELinux, so now tools would work across both.

I see from Google that the people that had developed setools back in the day have now developed an independent [selint](https://github.com/TresysTechnology/selint) tool, which seems to have some overlap in functionality with the tool we developed back in 2016. I think this is a case of convergent evolution, and I don't blame them for picking the same name - this project isn't active anymore, and it's not like we had a massive userbase in the first place :)

Having never tried the Tresys selint tool, but having used their setools tools and libraries in the past, I can strongly recommend that you give it a try. It probably works very well, and at least it is being actively developed.

Edit: is this the same "Microsoft SELint" you were referring to? https://www.youtube.com/watch?v=Gx5bxwvzN_Y

I didn't know Microsoft was involved. If it's the setools guys it's probably very good.
